import './globals.css'
import Header from '@/components/header'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-col gap-12'> 
  
        <Header /> 
        <div className='container mx-auto '>
          {children}
        </div>
      </body>

    </html>
  )
}
