import './globals.css'
import Header from '@/components/header';
import Footer from '@/components/footer';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// providers
import SplashScreenProvider from './providers/splash-screen-provider';
import ReduxToolkitProvider from './providers/redux-toolkit-provider';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ReduxToolkitProvider>
          <SplashScreenProvider>
            <div className='flex flex-col gap-12'>
              <Header />

              <div className='container mx-auto '>
                {children}
                <Footer />
              </div>
            </div>
          </SplashScreenProvider>
        </ReduxToolkitProvider>
      </body>

    </html>
  )
}
